# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-03 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('registration_number', models.BigIntegerField()),
                ('max_passangers_numb', models.IntegerField()),
                ('manufacture_year', models.IntegerField()),
                ('producer_model', models.CharField(max_length=100)),
                ('category', models.TextField()),
                ('is_Hybrid', models.BooleanField(default=True)),
            ],
        ),
    ]
