# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-04 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleet',
            old_name='producer_model',
            new_name='model',
        ),
        migrations.AddField(
            model_name='fleet',
            name='producer',
            field=models.CharField(default='Toyota', max_length=100),
            preserve_default=False,
        ),
    ]
